### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Greenleekd** [Esteban-Rocha/page-ruler-redux#1]
I like your extension so I am reviewing it and I would like to use your icon so that people in my school could identify it when they find it in the chrome store. If I could get written permission for it that would be great!

Thank you,
Greenleekd

**Comment by Esteban-Rocha** [comment]
Hi! thanks for your feedback! I'm currently setting the roadmap this week for the extension as I schedule time, so I'm estimating I'll be pushing source code from the extension on this week.

If you want to contribute just fork it and send me a PR that will be awesome, the icon you can get it from here [Icon](http://p.yusukekamiyamane.com/) it's on a Royalty-free license agreement you'll have to provide [attribution](http://p.yusukekamiyamane.com/icons/attribution/) if you want to use them for free.
