### ISSUE TITLE
Keyboard arrows shift don't work

### ISSUE THREAD

**Issue by Manyaka** [Esteban-Rocha/page-ruler-redux#12]
**Describe the bug**
Keyboard arrows shift don't work as I expected

**To Reproduce**
1. Click on Page Ruler browser extension.
2. Use mouse to rule elements
3. Release the mouse buttons, ruler still on the page
4. Want shift ruler up - use keyboard arrow Up
5. Ruler don't move

**Expected behavior**
Arrow Up move ruler up on 1px, arrow Down move ruler down on 1px

Desktop:
 - OS: Ubuntu 18.04.2
 - Browser: Google Chrome 72.0.3626.96
 - Page Ruler extension v 1.1.7

**Comment by Esteban-Rocha** [comment]
@Manyaka Trying to reproduce this, so far no success I wonder if this has to do something with ubuntu/unity (Asuming this is your DE, correct me if I'm wrong :slightly_smiling_face: ) global keybindings being conflicting with PPR. Will try to check on this on a VM when I got time as I'm mainly on arch and KDE. Thanks for filling in the issue.

**Comment by Manyaka** [comment]
> ubuntu/unity

I use GNOME 3

I checked this bug on version Page Ruler extension v 1.2.0 and it is not reproduce anymore. Thanks.

PS @Esteban-Rocha Who must close this bug? Me or you?

**Comment by Esteban-Rocha** [comment]
Awesome! thanks for letting me know! :clap:
