### ISSUE TITLE
please change colors! i can't read the values!

### ISSUE THREAD

**Issue by Maxhodges** [Esteban-Rocha/page-ruler-redux#2]
![dark2018-06-26 23-09-27](https://user-images.githubusercontent.com/957271/41917795-10b88de6-7996-11e8-8dd5-e080b285db24.png)

what were you thinking? it's too dark! impossible to read!

**Comment by Esteban-Rocha** [comment]
Hi! here's a screenshot just now

![image](https://user-images.githubusercontent.com/5914592/41922582-0ff580c8-792b-11e8-9e32-ac950043e8b1.png)

I'm thinking that maybe it's another extension of the website where you're working on has some conflicting css.

Please if you got some time to try to check what may be possible the issue or how I may be able to reproduce that, I'll gladly update it so it does not conflict like that for you or any other user, thanks.

**Comment by Esteban-Rocha** [comment]
Thanks! @d0lb33 will fix that on the upcoming days.

**Comment by alorson** [comment]
same here, its not usable with that bad Colors.

**Comment by alorson** [comment]
Any News on this?

**Comment by lewiscarvillesputnik** [comment]
This isn't fixed entirely as one of my websites the values have turned white on the white background input, therefore completely unreadable.

From a dev perspective I tend to just create a few CSS rules of my own with important declarations to override any of my CSS that might be causing issues with Page Ruler.

**Comment by Esteban-Rocha** [comment]
@lewiscarvillesputnik I will re visit this, the CSS is being moved onto SASS and it's a good couple of hours I have to put into to clean the legacy code, can you please share the URL so I can see this clearly and submit a patch for it?

Thanks.

**Comment by lewiscarville** [comment]
@Esteban-Rocha the URL is: https://www.turley.co.uk
