### ISSUE TITLE
Input Boxes are affected by site CSS

### ISSUE THREAD

**Issue by psydwannabe** [Esteban-Rocha/page-ruler-redux#8]
**Describe the bug**
When using the Page Ruler Redux Chrome plugin on a site which includes site-wide styling for text boxes, some of the styling is applied to the Page Ruler Redux text boxes which causes display issues (see screenshot below).

**To Reproduce**
1. With Page Ruler Redux enabled, visit any site which defines a height for input[type=number]
2. Turn on Page Ruler Redux
3. See the issue

**Expected behavior**
The Page Ruler panel is unaffected by site styling

**Screenshots**
![screen shot 2019-02-12 at 5 58 52 pm](https://user-images.githubusercontent.com/6654256/52681409-8af74380-2ef0-11e9-8cca-bb5d98c844e1.png)

**Desktop (please complete the following information):**
 - OS: macOS Sierra (10.12.6)
 - Browser: Chrome 72.0.3626.96
 - Version: Latest

**Comment by Esteban-Rocha** [comment]
@psydwannabe Thank you for filling up the issue with so much detail :confetti_ball:, I'll be releasing a patch for this soon!

**Comment by psydwannabe** [comment]
It's my pleasure! Thank you so much for keeping up this awesomely useful plugin!!  😁
